name: skillswap

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 5000:5000
    
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - skillswap
     
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: unless-stopped  
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 5173:5173
    command: npm run dev -- --host
    networks:
      - skillswap
    depends_on:
      - api
  
  redis:
    image: redis:latest # Use the latest official Redis image
    ports:
      - "6379:6379" # Expose Redis port if you need to access it from your host (e.g., for debugging)
    volumes:
      - redis_data:/data # Optional: Persist Redis data

volumes:
  redis_data:

networks:
  skillswap:
    driver: bridge