services:
  - type: web
    name: client
    env: docker
    plan: free
    dockerfilePath: client/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /

  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: server/Dockerfile
    envVars:
      - key: PORT
        value: 5000
    autoDeploy: true
